"""Generate the CLI reference pages (docs/pages/reference/cli/) from the cyclopts app.

Each page is rendered from the live command definitions, so the reference can
never drift from the code. A prek hook runs this on every commit and fails if
the output changes; regenerate manually with `just docs-cli`.
"""

import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

# cyclopts' App.generate_docs() does not expose generate_toc/no_root_title;
# the underlying documented function does.
from cyclopts.docs.markdown import generate_markdown_docs

from ttd.cli.app import app

OUT_DIR = Path(__file__).parent.parent / "docs" / "pages" / "reference" / "cli"

BANNER = "<!-- Generated by scripts/gen_cli_docs.py — do not edit. Regenerate: just docs-cli -->"


@dataclass
class Page:
    """One reference page: hand-written title/intro, generated command docs."""

    slug: str  # filename without .md
    title: str
    intro: str
    commands: list[str] = field(default_factory=list)  # root command/group names
    recursive: bool = True
    show_command_titles: bool = False  # H2 per command (multi-command pages)


PAGES = [
    Page(
        "client",
        "ttd client",
        "Manage the clients you bill. See the"
        " [Clients & projects guide](../../guides/clients-and-projects.md) for workflows.",
        commands=["client"],
    ),
    Page(
        "project",
        "ttd project",
        "Manage projects under your clients. See the"
        " [Clients & projects guide](../../guides/clients-and-projects.md) for workflows"
        " and how hourly rates resolve.",
        commands=["project"],
    ),
    Page(
        "entry",
        "ttd entry",
        "List and edit logged time entries. See the"
        " [Managing entries guide](../../guides/managing-entries.md).",
        commands=["entry"],
    ),
    Page(
        "timer",
        "Timer commands",
        "Start, inspect, and stop the live timer. ttd keeps at most one timer running;"
        " stopping it logs an entry. See [Tracking time](../../guides/tracking-time.md).",
        commands=["start", "stop", "status", "cancel"],
        show_command_titles=True,
    ),
    Page(
        "log",
        "ttd log",
        "Log time retrospectively with a natural-language time expression. See"
        " [Tracking time](../../guides/tracking-time.md) for workflows and"
        " [Time expressions](../time-expressions.md) for the full syntax.",
        commands=["log"],
    ),
    Page(
        "report",
        "ttd report",
        "Summaries of logged time by day, week, month, or arbitrary range. See the"
        " [Reports guide](../../guides/reports.md).",
        commands=["report"],
    ),
    Page(
        "invoice",
        "ttd invoice",
        "Create, render, and manage invoices. See the"
        " [Invoicing guide](../../guides/invoicing.md) for the full lifecycle.",
        commands=["invoice"],
    ),
    Page(
        "tax",
        "ttd tax",
        "Track tax set-aside and IRS estimated-tax payments. See the"
        " [Taxes guide](../../guides/taxes.md).",
        commands=["tax"],
    ),
    Page(
        "config",
        "ttd config",
        "Read and write configuration. See the"
        " [Configuration guide](../../guides/configuration.md) for layering and recipes,"
        " and the [configuration reference](../configuration.md) for every setting.",
        commands=["config"],
    ),
    Page(
        "db",
        "ttd db",
        "Database utilities: location, backups, health checks, and demo data. See"
        " [Data & backups](../../guides/data-and-backups.md).",
        commands=["db"],
    ),
    Page(
        "export",
        "ttd export",
        "Write entries to CSV, JSON, XLSX, or Apple Numbers. See"
        " [Import & export](../../guides/import-export.md) and the"
        " [interchange format reference](../interchange-format.md).",
        commands=["export"],
    ),
    Page(
        "import",
        "ttd import",
        "Bring entries in from CSV, JSON, XLSX, or Apple Numbers. See"
        " [Import & export](../../guides/import-export.md) and the"
        " [interchange format reference](../interchange-format.md).",
        commands=["import"],
    ),
]


def _escape_bracket_tokens(text: str) -> str:
    """Escape cyclopts' `**[required]**` / `*[default: …]*` markers.

    Unescaped they parse as unresolved markdown link references, which the
    Zensical build flags. They only ever appear in parameter bullets, never
    inside code blocks, so a targeted replacement is safe.
    """
    text = text.replace("**[required]**", r"**\[required\]**")
    return re.sub(r"\*\[default: ([^\]]*)\]\*", r"*\\[default: \1\\]*", text)


def _command_body(page: Page) -> str:
    parts = []
    for name in page.commands:
        sub = app[name]
        usage = f"ttd {name}" if len(page.commands) > 1 or not page.show_command_titles else None
        parts.append(
            _escape_bracket_tokens(
                generate_markdown_docs(
                    sub,
                    recursive=page.recursive,
                    heading_level=2,
                    generate_toc=False,
                    no_root_title=not page.show_command_titles,
                    usage_name=usage or f"ttd {name}",
                ).strip()
            )
        )
    return "\n\n".join(parts)


def _render_page(page: Page) -> str:
    return f"{BANNER}\n\n# {page.title}\n\n{page.intro}\n\n{_command_body(page)}\n"


def _first_help_line(name: str) -> str:
    help_text = app[name].help or ""
    return help_text.strip().splitlines()[0] if help_text.strip() else ""


def _index_row(page: Page) -> str:
    if len(page.commands) == 1:
        label = f"`{page.commands[0]}`"
        description = _first_help_line(page.commands[0])
    else:
        label = " · ".join(f"`{c}`" for c in page.commands)
        description = "Start, inspect, stop, or discard the live timer."
    return f"| [{label}]({page.slug}.md) | {description} |"


def _render_index() -> str:
    rows = "\n".join(_index_row(page) for page in PAGES)
    return f"""{BANNER}

# CLI reference

Everything ttd can do from the command line. Run `ttd <command> --help` for the
same information in your terminal.

```console
ttd [COMMAND]
```

Running bare `ttd` with no command launches [the TUI](../../guides/the-tui.md).

## Global options

| Option | Description |
| --- | --- |
| `--version`, `-V` | Print the ttd version. |
| `--install-completion` | Install shell completion (bash, zsh, or fish auto-detected). |
| `--help`, `-h` | Show help for any command. |

## Commands

| Command | Description |
| --- | --- |
{rows}
"""


def _strip_trailing_whitespace(text: str) -> str:
    """cyclopts output carries trailing spaces; the repo's whitespace hook
    would strip them and then this generator would put them back forever."""
    return "\n".join(line.rstrip() for line in text.splitlines()) + "\n"


def build_pages() -> dict[Path, str]:
    files = {OUT_DIR / "index.md": _render_index()}
    for page in PAGES:
        files[OUT_DIR / f"{page.slug}.md"] = _render_page(page)
    return {path: _strip_trailing_whitespace(content) for path, content in files.items()}


def main() -> int:
    check = "--check" in sys.argv[1:]
    files = build_pages()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    drifted: list[Path] = []
    for path, content in files.items():
        if path.is_file() and path.read_text() == content:
            continue
        drifted.append(path)
        if not check:
            path.write_text(content)
    for stale in sorted(OUT_DIR.glob("*.md")):
        if stale not in files:
            drifted.append(stale)
            if not check:
                stale.unlink()

    if drifted:
        verb = "out of date" if check else "regenerated"
        for path in drifted:
            print(f"{verb}: {path.relative_to(OUT_DIR.parent.parent.parent.parent)}")
        return 1 if check else 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
